# Generated by Django 2.2.16 on 2020-09-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200908_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='Task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
