# Generated by Django 2.2.16 on 2020-09-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200908_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task',
            new_name='title',
        ),
    ]
